### ISSUE TITLE
有些疑惑

### ISSUE THREAD

**Issue by Tim-Y-cloud** [guhang987/federated-learning#1]
1、tf.nn.softmax为什么就可以定义两层神经网络？我找很多都没有写
2、系统轮次：100？不应该是50吗？
3、本地轮次（EPOCH、E）： 5？不应该是10？
4、'x':
            #归一化
            np.array([source[0][i].flatten() / 255.0 for i in batch_samples],
                     dtype=np.float32),
        'y':
            np.array([source[1][i] for i in batch_samples], dtype=np.int32)
source[0/1][i]，y的标签为什么会在source[1]里面

**Comment by guhang987** [comment]
confidenceCV：
你好！
1. 不是定义，是针对y=wx+b的输出做一个softmax。这是多类线性回归模型，不知道能不能说成是神经网络
2、3: 原教程如此
4.x表示样本，y表示标签。source[0]存放了所有样本，source[1]存放了所有标签。
欢迎一起讨论。



------------------ 原始邮件 ------------------
发件人: confedenceCV <notifications@github.com&gt;
发送时间: 2020年10月25日 17:34
收件人: guhang987/federated-learning <federated-learning@noreply.github.com&gt;
抄送: Subscribed <subscribed@noreply.github.com&gt;
主题: 回复：[guhang987/federated-learning] 有些疑惑 (#1)





 
1、tf.nn.softmax为什么就可以定义两层神经网络？我找很多都没有写
 2、系统轮次：100？不应该是50吗？
 3、本地轮次（EPOCH、E）： 5？不应该是10？
 4、'x':
 #归一化
 np.array([source[0][i].flatten() / 255.0 for i in batch_samples],
 dtype=np.float32),
 'y':
 np.array([source[1][i] for i in batch_samples], dtype=np.int32)
 source[0/1][i]，y的标签为什么会在source[1]里面

**Comment by confedenceCV** [comment]
2,、3问题
我看了代码，配合你的注释，我发现系统轮次应该是50；本地轮次应该是100；
不知道是不是我理解出现了问题，希望得到你的解答

**Comment by Tim-Y-cloud** [comment]
2,、3问题
我看了代码，配合你的注释，我发现系统轮次应该是50；本地轮次应该是10；
不知道是不是我理解出现了问题，希望得到你的解答

**Comment by guhang987** [comment]
那就是我之后调了的吧，实验中一般会调很多参数包括本地论数、batchsize等，没有在注释中写明，抱歉。


发自我的iPhone

------------------ 原始邮件 ------------------
发件人: confedenceCV <notifications@github.com&gt;
发送时间: 2020年10月25日 18:39
收件人: guhang987/federated-learning <federated-learning@noreply.github.com&gt;
抄送: guhang <610203816@qq.com&gt;, Comment <comment@noreply.github.com&gt;
主题: 回复：[guhang987/federated-learning] 有些疑惑 (#1)





 
2,、3问题
 我看了代码，配合你的注释，我发现系统轮次应该是50；本地轮次应该是10；
 不知道是不是我理解出现了问题，希望得到你的解答

**Comment by guhang987** [comment]
close
